export const mockData = {
  users: [
    {
      email: "stephanskoric@gmail.com",
      password: "$2a$10$XCSGaphiz5Sp2qzAcSlb2uUXII.hEte1RPS00PsFZ/QzU7YOVIQUK",
      firstName: "Stefan",
      lastName: "Skoric",
      username: "stefan.skoric",
      dateOfBirth: "1993-03-18",
      type: "admin",
      createdAt: 1650131257215,
      status: "active",
      id: 1,
    },
    {
      email: "stephanskoric@gmail.com",
      password: "$2a$10$XCSGaphiz5Sp2qzAcSlb2uUXII.hEte1RPS00PsFZ/QzU7YOVIQUK",
      firstName: "Stefan",
      lastName: "Skoric",
      username: "maja.skoric",
      dateOfBirth: "1993-03-18",
      type: "user",
      createdAt: 1650051013641,
      status: "active",
      id: 2,
    },
    {
      email: "stephanskoric@gmail.com",
      password: "$2a$10$XCSGaphiz5Sp2qzAcSlb2uUXII.hEte1RPS00PsFZ/QzU7YOVIQUK",
      firstName: "Stefan",
      lastName: "Skoric",
      username: "sara.skoric",
      dateOfBirth: "1993-03-18",
      type: "user",
      createdAt: 1650051013641,
      status: "blocked",
      id: 2,
    },
  ],
  posts: [
    {
      id: 1,
      name: "Martinbrod waterfalls",
      place: "Bosnia and Herzegovina",
      accessibility: "Off-road vehicle",
      type: "Waterfall",
      description: "The beautiful waterfall i visited",
      userHandle: "stefan.skoric",
      createdAt: 1650051013641,
      upVotes: ["maja.skoric, sara.skoric", "jakov.skoric"],
      downVotes: ["user", "user.someone"],
      comments: [
        {
          author: "jakov.skoric",
          body: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
          createdAt: 1650051013641,
          id: 1,
        },
        {
          author: "maja.skoric",
          body: "s simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets c",
          createdAt: 1650051013641,
          id: 2,
        },
        {
          author: "sara.skoric",
          body: "Awesome place!",
          createdAt: 1650051013641,
          id: 3,
        },
        {
          author: "user",
          body: "Great place!",
          createdAt: 1650051013641,
          id: 4,
        },
      ],
    },
    {
      id: 2,
      name: "Rainforest",
      place: "Bosnia and Herzegovina",
      accessibility: "It's not possible to come by vehicle",
      type: "Forest",
      description: "The beautiful waterfall i visited",
      userHandle: "stefan.skoric",
      createdAt: 1650051013641,
      upVotes: ["maja.skoric, sara.skoric", "jakov.skoric", "user"],
      downVotes: ["user", "user.someone"],
      comments: [
        {
          author: "jakov.skoric",
          body: "Awesome place!",
          createdAt: 1650051013641,
          id: 2,
        },
      ],
    },
    {
      id: 3,
      name: "Lake",
      place: "Bosnia and Herzegovina",
      accessibility: "It's not possible to come by vehicle",
      type: "Excursion site",
      description: "The beautiful waterfall i visited",
      userHandle: "stefan.skoric",
      createdAt: 1650051013641,
      upVotes: ["maja.skoric, sara.skoric", "jakov.skoric", "user"],
      downVotes: ["user", "user.someone"],
      comments: [
        {
          author: "jakov.skoric",
          body: "Awesome place!",
          createdAt: 1650051013641,
          id: 3,
        },
      ],
    },
  ],
};
